### ISSUE TITLE
Version gets bumped when no fix/feat commits present in history

### ISSUE THREAD

**Issue by MisterTimn** [TomerFi/version-bumper#76] opened 2022-07-28 07:23 UTC
### What happened?

When launching version bumper with no commits since latest tag or only docs/chore/build commits, a patch version gets bumped regardless.

**Expected:** version-bumper gives no new version or the same version as last tag.

Provided log output of the action but results are the same using the docker image directly

### Image Version

2.0.4

### Relevant log output

```shell
[Release/release-needed]   🐳  docker create image=act-tomerfi-version-bumper-action-1-1-3-dockeraction:latest platform= entrypoint=[] cmd=["true" "conventionalcommits" ".dev" "/github/workspace/"]
[Release/release-needed]   🐳  docker run image=act-tomerfi-version-bumper-action-1-1-3-dockeraction:latest platform= entrypoint=[] cmd=["true" "conventionalcommits" ".dev" "/github/workspace/"]
| /usr/local/scripts/entrypoint.sh: line 79: cd: /github/workspace/: No such file or directory
[Release/release-needed]   ⚙  ::set-output:: new_version=v22.7.2
[Release/release-needed]   ⚙  ::set-output:: next_dev_iteration=v22.7.3.dev
[Release/release-needed]   ⚙  ::set-output:: major_part=v22
[Release/release-needed]   ⚙  ::set-output:: minor_part=7
[Release/release-needed]   ⚙  ::set-output:: patch_part=2
[Release/release-needed]   ⚙  ::set-output:: patch_next_dev=3.dev
[Release/release-needed]   🐳  docker exec cmd=[chown -R 0:0 /home/jveessen/obelisk/obelisk] user=0 workdir=
[Release/release-needed]   ✅  Success - Main Run bumper
[Release/release-needed] ⭐ Run Main echo ${{ steps.bumper.outputs.new_version }}
cat changelog-${{ steps.bumper.outputs.new_version }}.md
[Release/release-needed]   🐳  docker exec cmd=[bash --noprofile --norc -e -o pipefail /var/run/act/workflow/3] user= workdir=
| v22.7.2
| ### [v22.7.2](https://github.com/idlab-discover/obelisk/compare/v22.7.1...v22.7.2) (2022-07-28)
|
```

**Comment by TomerFi** [comment] 2022-07-29 05:26
Thanks for reporting - I will look into it this weekend.

**Comment by MisterTimn** [comment] 2022-07-29 07:53
I've noticed that tools like npm standard-version and conventional changelog also have the same behavior so this might be from a dependant and intended behavior (though I find it a bit counter intuitive 🤷)

**Comment by TomerFi** [comment] 2022-07-30 06:31
> ### What happened?
> When launching version bumper with no commits since latest tag or only docs/chore/build commits, a patch version gets bumped regardless.

**For no commits**
This is **not a bug**, that is the **desired behavior**.

The `version-bumper` is meant to run once you decide you want to release your application.
If you don't want to release your application - don't run the `version-bumper`.
I recommend writing some sort of automation around the following git command:

```
git rev-list --count HEAD ^origin/dev
```
| replace `origin/dev` with your base remote/base_branch.

**For docs/chore/build type commits**
This is **not a bug**, that is the **desired behavior**.

As stated in `version-bumper`'s docs, this tool is built around the concept and specifications of [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/).
Based on these specifications, the commit types you listed (docs/chore/build), if not marked as breaking, will result in a patch bump.

We might be able to add configuration allowing users to exclude specific commit types, that might even be a good idea.
But pre-excluding specific types, will never be the default behaviour as long as it diverge from the conventional commits specifications.

---

> **Expected:** version-bumper gives no new version or the same version as last tag.

This doesn't fit the design and purpose of the `version-bumper`, as explained above, the `version-bumper` is meant to be run once you decide to release your application, it is not meant to replace any automation running prior, determining whether or not a release even needs to happen.

That means, when running the `version-bumper`, we fully intend on releasing our application. If the `version-bumper` will spit out an existing release number, the release workflow will probably fail miserably, and this will be very much counterintuitive.

**Comment by TomerFi** [comment] 2022-07-30 06:37
In regards to adding the ability to configure the tool and exclude specific types,
I can't say I'm totally on board with this, as mentioned above.

The purpose of this tool is to calculate the next semver version,
not to decide whether or not a release is even required, that sounds like a job for automation.

That being said - I would consider adding a configuration for excluding types,
and to have the said configuration make the tool fail,
but I don't think having it spit out an existing version is a good practice.

Please feel free to contribute.

**Closed** 2022-07-30 06:39 UTC
